#CREATE DATABASE university2lww;
USE university2lww;

CREATE TABLE IF NOT EXISTS FACULTY
(
FID CHAR(8),
LastName VARCHAR(20) NOT NULL,
FirstName VARCHAR(20) NOT NULL,
Rank CHAR(4),
Tenured CHAR(1),
DeptID CHAR(4),
PRIMARY KEY (FID),
FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DID)
);

CREATE TABLE IF NOT EXISTS STUDENT
(
STID CHAR(8),
LastName VARCHAR(20) NOT NULL,
FirstName VARCHAR(20) NOT NULL,
Major CHAR(4),
Level CHAR(2),
GPA DECIMAL(4,3),
AdvisorID CHAR(8),
PRIMARY KEY (STID),
FOREIGN KEY (AdvisorID) REFERENCES FACULTY(FID)
);
CREATE TABLE IF NOT EXISTS Course
(
CID CHAR(8),
Dept CHAR(4),
Title VARCHAR(50),
Credits SMALLINT,
PRIMARY KEY (CID),
FOREIGN KEY (Dept) REFERENCES DEPARTMENT(DID)
);
CREATE TABLE IF NOT EXISTS Section
(
SectID CHAR(6),
CourseID CHAR(8) NOT NULL,
SectionNumber CHAR(3) NOT NULL,
Semester CHAR(4) NOT NULL,
Year CHAR(4) NOT NULL,
InstructorID CHAR(8),
PRIMARY KEY (SectID),
FOREIGN KEY (CourseID) REFERENCES COURSE(CID),
FOREIGN KEY (InstructorID) REFERENCES FACULTY(FID)
);
CREATE TABLE IF NOT EXISTS Class
(
SectID CHAR(6),
StudentID CHAR(8),
Grade CHAR(2),
PRIMARY KEY (SectID, StudentID),
FOREIGN KEY (SectID) REFERENCES SECTION(SectID),
FOREIGN KEY (StudentID) REFERENCES STUDENT(STID)
);

